language: php

dist: xenial

services:
  - mysql
  - postgresql

env:
  global:
    - COMPOSER_ROOT_VERSION="3.x-dev"

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1 RECIPE_VERSION="^1 --prefer-lowest"
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1 RECIPE_VERSION="^1"
    - php: 7.1
      env: DB=PGSQL PHPUNIT_TEST=1 RECIPE_VERSION="^4 --prefer-lowest"
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1 RECIPE_VERSION="^4"
    - php: 7.3
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1 RECIPE_VERSION="4.x-dev"
    - php: 7.4
      env: DB=MYSQL PHPUNIT_COVERAGE_TEST=1 RECIPE_VERSION="4.x-dev"

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require silverstripe/recipe-cms:$RECIPE_VERSION --no-update
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:^2 --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ *.php; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
