name: Merge-up

on:
  # At 12:10 PM UTC, only on Thursday
  schedule:
    - cron: '10 12 * * 4'
  workflow_dispatch:

jobs:
  merge-up:
    name: Merge-up
    # Only run cron on the symbiote account
    if: (github.event_name == 'schedule' && github.repository_owner == 'symbiote') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Merge-up
        uses: silverstripe/gha-merge-up@v1
